### ISSUE TITLE
想个好名字 

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro#10]
npm name: totoro
domain name: totorojs.org

来自宫崎骏的动画《龙猫》中的主角名：豆豆龙

**Comment by lifesinger** [comment]
itest 可以作为备选

总的或许可以叫 PageQuality   类似 PageSpeed

或者从 Arale 动画里找一个角色，类似 nico 这种

大家集思广益多提提备选

On Thu, Jan 31, 2013 at 7:16 PM, fool2fish notifications@github.com wrote:

> todo
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/alipay/wd-qc-tools/issues/10.

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by afc163** [comment]
bee

**Comment by fool2fish** [comment]
lan
兰

来自柯南的女朋友小兰
侦探动漫人物，外表甜美，身手不凡，和测试有那么点关系哈哈

**Comment by fool2fish** [comment]
@afc163 bee？什么由来啊？

**Comment by afc163** [comment]
蜜蜂，哔哔哔

**Comment by lifesinger** [comment]
lan 联想到 兰 挺好的，小清新呀

不过

也容易联想到 烂……

On Thu, Jan 31, 2013 at 9:54 PM, afc163 notifications@github.com wrote:

> 密封，哔哔哔
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/alipay/wd-qc-tools/issues/10#issuecomment-12943086.

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by lepture** [comment]
mincho 明朝

**Comment by lifesinger** [comment]
要看 npm 中是否有注册
