### ISSUE TITLE
repo 不支持自定义

### ISSUE THREAD

**Issue by leoner** [totorojs/totoro#106]
```
new TotoroClient({
    repo: 'totorox'
})
```

目前不支持在通过 api 方式调用的时候传递 repo 参数.
原因是因为在 totoro 中强制通过 getRepo 的方式获取 repo.

**Comment by fool2fish** [comment]
为什么要支持自定义？

**Comment by leoner** [comment]
```
totoro --code="typeof 1"
```

如果以这种形式执行的话，repo 的内容是有问题的，所以对于这种方式可以给一个特殊的标示进行区分。

**Comment by fool2fish** [comment]
运行类型可以通过已有数据分析得出，在 tla 中，每条记录有一个 __statsCode 字段，0 为 --code， > 0 为单元测试（1 为测试成功，>=2 为各种类型的失败），<0 预留给功能测试了
