### ISSUE TITLE
开启coverage的命令和配置是```?

### ISSUE THREAD

**Issue by wiz-Cll** [totorojs/totoro#109]
> --skip-coverage
> 关闭代码覆盖率检查.
> 默认：开启

那么开启覆盖率检查的配置是什么?  --skip-coverage=false  或  on  或 close都试过了,无效.

**Comment by fool2fish** [comment]
你是想看到覆盖率百分比还是说哪些行覆盖到了，哪些没覆盖？

看百分比结果的话，默认就是有覆盖率的，每个浏览器完成后后面跟的 (coverage 100%) 字样就是覆盖率
--skip-coverage 这个选项开启，就没有这个覆盖率输出了
因为是自动处理的，所以如果代码写得比较奇怪，可能没有办法自动做这个事情

如果想看到具体哪些没有覆盖到，目前这个功能在内测，还没有正式开放给用户用

**Comment by wiz-Cll** [comment]
直接在example/jasmine中运行totoro命令
看不到覆盖率...
........

  chrome 30.0.1599.101 / macosx 10.9.0
  Passed all of 6 tests in 48ms

没有百分比的coverage...

**Comment by fool2fish** [comment]
你仔细看下那个例子，是没有源码的哦，就是没有 src 文件，jasmine 的例子纯粹只是演示 jasmine 也是可以用的

只有你的项目中有 src 或者 lib 文件夹时，里面的代码才会被认为是源码，totoro 会计算测试覆盖率

**Comment by wiz-Cll** [comment]
哦... got it~  谢谢~
