### ISSUE TITLE
跑通 thrill + queen + selenium grid

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro#11]
确保机器上已经安装了 [Java](http://www.java.com/en/download/index.jsp) 和 [node](http://nodejs.org/)。

**注意：**简单起见，文中都给出了推荐端口，如有必要，可自行替换。
### 一、启动 selenium-grid hub

1、下载最新的 [selenium-server-standalone-{{version}}.jar](https://code.google.com/p/selenium/downloads/list)（本文档使用 2.29.0 版本） 到任意目录，本文档假定该目录为 totoro-server 。

2、在同目录下创建 hub.json 配置文件。

```
{
    "host": "{{grid-hub-host}}",
    "port": 4444,
    "newSessionWaitTimeout": -1,
    "servlets" : [],
    "prioritizer": null,
    "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
    "throwOnCapabilityNotPresent": true,
    "nodePolling": 5000,
    "cleanUpCycle": 5000,
    "timeout": 300000,
    "browserTimeout": 0,
    "maxSession": 5
}
```

更多 hub 配置项请参见 [Selenium Wiki](http://code.google.com/p/selenium/wiki/Grid2)

3、命令行启动 selenium-grid hub

```
java -jar selenium-server-standalone-2.29.0.jar -role hub -hubConfig hub.json
```
### 二、启动 selenium-grid node

1、下载最新的 [selenium-server-standalone-{{version}}.jar](https://code.google.com/p/selenium/downloads/list) 到任意目录。如果 node 和 hub 在同一台机器上，则可跳过此步骤。

2、在同目录下创建 node.json：

```
{
    "capabilities": [
        {
            "browserName": "iexplorer",
            "version": "9",
            "maxInstances": 5,
            "seleniumProtocol": "WebDriver"
        },
        {
            "browserName": "firefox",
            "maxInstances": 5,
            "seleniumProtocol": "WebDriver"
        }
    ],
    "configuration": {
        "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
        "maxSession": 5,
        "port": 5555,
        "host": "{{grid-hub-host}}",
        "register": true,
        "registerCycle": 5000,
        "hubPort": 4444,
        "hubHost": "{{grid-node-host}}"
    }
}
```

你可以修改 capabilities 中的选项以确保符合你的要求。其中：
- firefox 仅支持 17 及以下的版本。
- 除 `firefox` 外，一般其他浏览器都需要 [安装驱动程序](http://seleniumhq.org/download/)，包括 chrome 和 ie。
  - 强烈建议所有浏览器都安装到默认路径。因为 opera 和 safari 的驱动是 jar 包内置的，需要它们安装在默认路径才能识别。
  - 通常安装驱动的方法是将驱动文件存放的路径加入环境变量 Path，但由于 ie9 可能存在某些安全限制，推荐将 ie 驱动直接放置到 system32 目录下而不设置 Path。
  - ie 的驱动需要注意 32和64位操作系统的区别。
- ie 最好指定 version 。指定版本的 ie browserName 为 "iexplorer"，不指定版本的 ie browserName 为 "*iexplore" 。

更多 node 配置项请参见 [Selenium Wiki](http://code.google.com/p/selenium/wiki/Grid2)

3、命令行启动 selenium-grid node

```
java -jar selenium-server-standalone-2.29.0.jar -role node -nodeConfig node.json
```

打开 {{grid-hub-host}}:4444/grid/console，如果正常的话，应该能看到连接上的 node 的浏览器信息。
### 三、运行 queen

1、下载 [queen](https://github.com/fool2fish/queen) 到任意目录，为方便调试，使用的是源码。如和 hub 是同一台机器，建议下载到同一目录。

2、安装依赖。进入 queen/ 目录运行：

```
npm update
```

3、修改 queenConfig.js，确保符合你的需求：

```
module.exports = {
    capture:"{{queen-host}}:9000",
    populator: {
        type: "selenium",
        config: {
            host: '{{selenium-hub-host}}', 
            port: 4444
        },
        clients: [
            { browserName: "iexplorer", version: "6" },
            { browserName: "iexplorer", version: "7" },
            { browserName: "iexplorer", version: "8" },
            { browserName: "iexplorer", version: "9" },
            { browserName: "chrome"},
            { browserName: "firefox"},
            { browserName: "opera"},
            { browserName: "safari"}
        ]
    }
};
```

注意：
- capture 为 queen 的服务地址，这里 host 如果配置为 “localhost” 或者 “127.0.0.1”，则只能本机访问。如多台机器操作，需填写真实 IP 或域名。
- clients 中配置的浏览器和配置必须是 selenium-grid 服务支持的，否则会报错。

4、 命令行运行：

```
node ../../bin/queen
```

如启动成功，则 selenium-grid 会自动打开 url：http://{{queen-host}}:9000/?clientId={{selenium-id}}
### 四、运行 thrill

注意：此步骤以后会由 totoro 客户端替换掉

1、客户端机器安装 thrill

```
sudo npm install -g thrill
```

2、运行测试

```
thrill -h {{queen-host}}:9200 path/to/runner.html
```

注意：thrill 运行的位置没有特别的要求，只要 runner 的路径传递正确即可。

**Comment by fool2fish** [comment]
@leoner 

TODO：
- 浏览器重启的时间间隔
- thrill 自定义要测试的浏览器

**Comment by leoner** [comment]
- 浏览器重启的时间间隔,也可以说是闲置超时。
  在启动 hub 的 hub.json 中配置

``` json
{
  "host": "localhost",
  "port": 4444,
  "newSessionWaitTimeout": -1,
  "servlets" : [],
  "prioritizer": null,
  "capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher",
  "throwOnCapabilityNotPresent": true,
  "nodePolling": 5000,

  "cleanUpCycle": 5000,
  "timeout": 30000,
  "browserTimeout": 0,
  "maxSession": 5
}
```

**Comment by lifesinger** [comment]
今天看了沉鱼的演示，感觉我们正在朝着正确的方向上前行
踏下心来努力去做好做精
很相信我们能在前端测试领域做出一番不一样的事情来

新年快乐。

On Thu, Feb 7, 2013 at 4:15 PM, hui.kang notifications@github.com wrote:

>    -
> 
>    浏览器重启的时间间隔
>    在启动 hub 的 hub.json 中配置
> 
>    {"host": "localhost","port": 4444,"newSessionWaitTimeout": -1,"servlets" : [],"prioritizer": null,"capabilityMatcher": "org.openqa.grid.internal.utils.DefaultCapabilityMatcher","throwOnCapabilityNotPresent": true,"nodePolling": 5000,
>    "cleanUpCycle": 5000,"timeout": 30000,"browserTimeout": 0,"maxSession": 5}
> - timeout 应该是指定 session 的过期时间，如果到达指定时间，grid 将认为浏览器的 session 已经过期，将会重新打开指定的 url. 目前这个是 30s 就会重启浏览器。
>   
>   —
>   Reply to this email directly or view it on GitHubhttps://github.com/alipay/wd-qc-tools/issues/11#issuecomment-13225971.

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by leoner** [comment]
grid 的 node.json 和 queenConfig.json 的配置在 ie 下需要注意下
node.json

``` json
{
    "browserName": "iexplorer",
    "version": "9",
    "maxInstances": 5,
    "seleniumProtocol": "WebDriver"
}
```

如果我们对 ie 指定版本的话，记住 browserName 一定是 _iexplorer_ 而不是 ***iexplorer**
queenConfig.json

``` json
clients: [
    { browserName: "iexplorer", version: "6" },
    { browserName: "iexplorer", version: "7" },
    { browserName: "iexplorer", version: "8" },
    { browserName: "iexplorer", version: "9" },
    { browserName: "chrome"},
    { browserName: "firefox"},
    { browserName: "opera"},
    { browserName: "safari"}
]
```
