### ISSUE TITLE
totoro支持fixture吗?

### ISSUE THREAD

**Issue by wiz-Cll** [totorojs/totoro#110]
需要测试一些函数对html的操作, 使用jasmine的fixture插件jasmine-jquery, 在每个it前载入一个测试的html页面,然后进行选择或类名操作等的测试,但是无论是看--verbose输出的测试细节还是抓住一点点时间看弹窗中的network, 都没有载入相应的fixture页面啊...
labor连接server后执行测试时弹出的页面不能进行这样的操作吗?

代码如下:

```
 describe('util 工具库测试 with fixtures', function(){
    beforeEach(function(){
        jasmine.getFixtures().clearCache();
        jasmine.getFixtures().containerId = 'TDD-fixture';
        jasmine.getFixtures().fixturesPath = '/blog/tests/fixture';
        loadFixtures('blog_fixture.html');
        // loadStyleFixtures('../../../fixture/style.css');
    });

    it('util.qs() should be able to query out ul', function(){
        // expect( $( util.qs('#TDD-fixture ul#util-query') ) ).toContain('li');
        expect( util.qs('#TDD-fixture ul#util-query').innerText ).toEqual('');
    });
```

执行的结果报的错误是完全选择不到节点, 明显是fixture没有load进来...

**Comment by fool2fish** [comment]
1. 默认必须确保所有相对引用的资源在一个项目目录下（因为本地会起一个 http 服务，如果超出当前目录，就请求不到了），比如你那个 `loadStyleFixtures('../../../fixture/style.css')` 应该就不是在本项目目录下的，那么就需要设置 `totoro` 的 `--client-root` 为你所有资源的最小根目录。
2. 我不是很熟悉 fixture，但是看代码，应该是异步操作？如果是异步的话，这样写会有问题，具体可以参考下 jasmine 的 Asynchronous Support 部分。
