### ISSUE TITLE
建议实现watch

### ISSUE THREAD

**Issue by meetwudi** [totorojs/totoro#115]
在文件变动的时候重新启动测试

**Comment by hotoo** [comment]
我觉得没必要。push 的时候测试就够了，最多到 commit。

**Comment by lepture** [comment]
@tjwudi 同意 @hotoo 

另外，如果你真有这个需求，可以使用：https://github.com/lepture/rewatch

**Comment by fool2fish** [comment]
totoro 只会关注其核心功能的实现，其他功能可以自己组装来使用哦，ps，因为 totoro 是解决测试兼容性问题的，所以每次运行测试消耗比较大（意味着一个测试可能需要几秒甚至更长时间来完成测试），频繁存档存档可能会导致totoro同时运行好几个你在编写的测试代码，这样也比较晕吧：）

watch 功能可以试试看 @lepture 的推荐咯
