### ISSUE TITLE
npm install 速度那个慢。。。

### ISSUE THREAD

**Issue by fengmk2** [totorojs/totoro#116]
建议文档加上 npm install --registry=http://r.cnpmjs.org

**Comment by hotoo** [comment]
这个应该是用户 npm config 的事。

**Comment by fengmk2** [comment]
很多用户不知道，算是给他们一个tips
2014年2月17日 AM10:45于 "闲耘™" notifications@github.com写道：

**Comment by fool2fish** [comment]
没有问题，可以加个提示，让国内用户使用你们得镜像：）

**Comment by fengmk2** [comment]
哈哈，多谢，争取让它变成我们的镜像
2014年2月17日 AM10:51于 "Zhouxuan Yang" notifications@github.com写道：
