### ISSUE TITLE
code coverage result missing

### ISSUE THREAD

**Issue by fengmk2** [totorojs/totoro#117]
看文档是默认开启coverage的，但是我本地测试一下没成功。

![image](https://f.cloud.github.com/assets/156269/2182002/e155ec94-9775-11e3-87de-aff616aec921.png)

**Comment by fool2fish** [comment]
覆盖率确实是默认开启，但是能得出覆盖率数据需要满足两条件： 1、要有源码文件 2、totoro 可以正确找出源码。

你跑得是 totoro 的例子，打开下这个文件夹，你看看是没有源码的哦，就是没有 src 文件夹，只有测试文件，所以就没有测试覆盖率了。

你可以随便测一个有源码的测试用例，比如 `totoro --runner=http://aralejs.org/base/tests/runner.html` 来测

**Comment by fengmk2** [comment]
好吧，因为我是按readme来跑的，看readme截图有结果，就这么想了。
2014年2月17日 AM10:48于 "Zhouxuan Yang" notifications@github.com写道：

**Comment by fool2fish** [comment]
多谢提醒，readme 写错了，应该是跑 simple 那个例子的，那个有源码。我改一下文档再关这个 issue。

**Comment by fengmk2** [comment]
好的，给力！
2014年2月17日 AM10:53于 "Zhouxuan Yang" notifications@github.com写道：
