### ISSUE TITLE
如何配置过时时间

### ISSUE THREAD

**Issue by RubyLouvre** [totorojs/totoro#125]
报了这样一个BUG

```
  ms-duplex-bool > async: timeout of 2000ms exceeded
```

**Comment by fool2fish** [comment]
这个跟你的测试框架有关系，在不同浏览器里速度不一样，慢得可能会超时，找下你测试框架的选项。
ps：如果总体超过5分钟，totoro 会超时，这是会显示 Client timeout。这种情况这是 --timeout 就好了。
