### ISSUE TITLE
JS如何模拟选择 下拉框 的一个option元素呢？

### ISSUE THREAD

**Issue by RubyLouvre** [totorojs/totoro#126]
如果是模拟点击一个元素,很简单,直接el.click()  求指教~

**Comment by fool2fish** [comment]
jquery,arale,kissy 都有这种功能的，这个是 arale 体系下看下就知道了，https://github.com/totorojs/event-simulate

**Comment by RubyLouvre** [comment]
thanks !我去看看

**Comment by lifesinger** [comment]
司徒，QCon 你们公司有啥议题想分享分享不?

On Mon, Mar 17, 2014 at 3:47 PM, 司徒正美 notifications@github.com wrote:

> Closed #126 https://github.com/totorojs/totoro/issues/126.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro/issues/126
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香
