### ISSUE TITLE
如何使用totoro-config.json啊(主要是想让它自动打开浏览器)?

### ISSUE THREAD

**Issue by RubyLouvre** [totorojs/totoro#129]
我有一个测试项目,文件名为avalon.test,下面就是src与tests文件夹,
然后我看你们的例子在avalon.test的目录下再加上totoro-config.json

```
{
  "browsers": ["chrome", "ie", "firefox"],
  "host": "127.0.0.1",
  "port": 9999
}
```

然后全局安装你那三个家伙

```
npm install totoro-server -g
npm install totoro -g
npm install browsers -g
```

然后打开控制台 totoro-server

然后打开另一个控制台 定位到avalon.test目录下
然后totoro config 没有自动打开浏览器啊!!!!!!!!

**Comment by leoner** [comment]
浏览器目前不会自动打开，需要通过 browsers 进行打开。
browsers 是负责浏览器守护的。

**Comment by RubyLouvre** [comment]
我就是想让 browsers 打开

**Comment by RubyLouvre** [comment]
$ browsers --capture=totorojs.org 能直接 $ browsers --capture=192.168.123.56吗 但我还是想让它集成totoro-config.json 中

**Comment by RubyLouvre** [comment]
像karma就比较智能了，不像totor分得很碎，不能自动化

**Comment by fool2fish** [comment]
karma 是单机系统，不是分布式的啊，ms不能这么比吧。你想看，即使可以这么做，也不可能配置这么少就能解决问题的（因为你不能在一个系统上打开所有的浏览器），totoro 的设计遵循小而独立的理念。不过你的需求么也合理的，所以下一个版本可能会改进。先这么用着好了：）我们自己也是这样，browsers 守护的机器基本不太需要关注的。ps：server 和 browsers 可以用 pm2 守护。
