### ISSUE TITLE
请问如何用totoro测试线上功能？

### ISSUE THREAD

**Issue by sodawy** [totorojs/totoro#130]
例子都是测试本地静态资源。请问能不能测试指定线上业务？

1、能打开线上url页面，比如hotel.qunar.com
2、对打开的页面，能把测试case注入到页面js沙箱。可以让case操作页面dom，事件等。
3、对打开的页面，有没有捕获js异常的事件？

多谢！

**Comment by fool2fish** [comment]
1. 能打开线上 url `totoro -R url`
2. 测试脚本注入的事情需要用户自己实现，totoro 只管运行
3. 有捕获 js 异常，看 example/syntax-error 的例子

**Comment by sodawy** [comment]
感谢回复！
