### ISSUE TITLE
申请测试服务器

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro#14]
暂定申请2台服务器

需满足如下条件：
- 固定 ip
- 可安装 windows（要能同时跑ie6789几个版本）
- 不被干扰（因为会操作浏览器，不能被人为关掉）
- 便于管理操作（目前看起来代码可能不是很稳定）

**Comment by fool2fish** [comment]
联系 王中元 和 梦棠

3个备选方案：
1. 实体机
2. 虚拟机
3. 阿里云

相关人员本周未到岗，下周跟进，如无意外，下周可搞定

**Comment by lifesinger** [comment]
有任何需要我的地方，别犹豫

2013/2/22 fool2fish notifications@github.com

> 联系 王中元 和 梦棠
> 
> 3个备选方案：
> 1. 实体机
> 2. 虚拟机
> 3. 阿里云
> 
> 相关人员本周未到岗，下周跟进，如无意外，下周可搞定
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/alipay/totoro/issues/14#issuecomment-13932878.

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by fool2fish** [comment]
想要直接装xp和win7的服务器，各种软磨硬泡啊，sa说只能装 windows 2003 server，然后自己要再装个虚拟机跑xp和win7，说是直接装网络跑不通，但这样跑又太ws，况且 ie 很很容易挂。打听到淘宝的测试服务器是可以直接装的，找了下人，让sa联系去了。希望有个好结果。

**Comment by leoner** [comment]
好吧，这也要托关系，太不容易了呀！

**Comment by fool2fish** [comment]
成功弄到安装了指定操作系统的机器，真心不容易。结贴。
