### ISSUE TITLE
totoro --code 参数值的一致性

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro#140]
```
if (/\.js$/.test(code)) {
  script = '<script src="' + code + '"></script>'
} else {
  script = '<script>console.log(' + code + ')</script>'
}
```

当传入文件路径时，需要自己写 `console.log` 语句才能打印出想查看的值，但是传入代码片段时，则整个片段当表达式处理。这样设计的原因是不希望使用者写 `totoro --code "console.log(xxx)"` 这么麻烦，但损失了一致性，且不可打印多个值。

ps：由于传入文件路径可能是完整路径之类的，为确保正确，需要求一次相对路径

**Comment by fool2fish** [comment]
同时支持  `totoro --code document.body` 和 `totoro --code "console.log(document.body)"`

**Comment by afc163** [comment]
没有修改？

**Comment by fool2fish** [comment]
改了啊，新版本，还在分支中，近期发布

**Comment by afc163** [comment]
木有关联 commit 。

**Comment by fool2fish** [comment]
大改动里顺手改得，提交的时候没关联，不过分支也确实不显示关联，有也要合并到主干才显示
