### ISSUE TITLE
启动server报错

### ISSUE THREAD

**Issue by wf123537200** [totorojs/totoro#142]
![issus](https://cloud.githubusercontent.com/assets/5130528/4839633/4362779e-6003-11e4-8102-8b2f96ff08ac.png)
window7, 64bit，执行npm install -g totoro-server后，执行totoro-server报如上图错误，查看错误代码后发现只要将此错误消除，就可以执行成功，以下是ansi.js中修改后的代码
function is256ColorSupported() {
  if (!isColorSupported()) return false;

  var term = process.env.TERM || ‘256’;// 在这里增加256代码
  term = term.toLowerCase();
  return term.indexOf('256') !== -1;
}

麻烦帮忙看下，谢谢!

**Comment by fool2fish** [comment]
这个问题被反馈多次，升级 colorful 依赖即可修复。我们马上要发布 2.0 版本，要不考虑从源码分支安装 totoro-server 和 totoro?

**Comment by wf123537200** [comment]
开发版现在稳定可用吧，之前担心开发版不稳定，所以没有使用。

那我改用源码分支了哈~

发件人: Zhouxuan Yang [mailto:notifications@github.com] 
发送时间: 2014年10月30日 16:44
收件人: totorojs/totoro
抄送: loveSed
主题: Re: [totoro] 启动server报错 (#142)

这个问题被反馈多次，升级 colorful 依赖即可修复。我们马上要发布 2.0 版本，要不考虑从源码分支安装 totoro-server 和 totoro?

**Comment by wf123537200** [comment]
对了，或者直接从源码copy新的colorful来进行覆盖应该也素可以的吧~~？

发件人: Zhouxuan Yang [mailto:notifications@github.com] 
发送时间: 2014年10月30日 16:44
收件人: totorojs/totoro
抄送: loveSed
主题: Re: [totoro] 启动server报错 (#142)

这个问题被反馈多次，升级 colorful 依赖即可修复。我们马上要发布 2.0 版本，要不考虑从源码分支安装 totoro-server 和 totoro?

**Comment by fool2fish** [comment]
分支已内测多日，即将发布，应该不会有大问题。当然，你直接在老版本上手工安装更高版本的 colorful 依赖也可以哦：）
