### ISSUE TITLE
totorojs和karma的定位以及区别?

### ISSUE THREAD

**Issue by atian25** [totorojs/totoro#150]

**Comment by fool2fish** [comment]
一般来说，测试分为两部分：1. 测试框架 2. 测试工具

totorojs 是一个单纯的分布式自动化测试工具，你可以使用任意测试框架来编写测试（totorojs 对你选用 什么测试框架没有任何约束），并且将这些测试发送到目标机器上指定特定的浏览器进行测试

karma 则对测试框架有一定的约束，如果你看过 karma 的官方文档，就会知道如果要用 karma 进行测试，必须要遵循 karma 的一些约定来些测试代码，karma 也是一个测试工具，但不是分布式的，而是单机模式，自动调用你电脑上安装的浏览器来进行测试

所以两者各有侧重，你可以根据自己的需要选择使用什么工具来测试，如果你的代码要兼容所有的主流浏览器，那么 totorojs 刚好能胜任这个工作，如果你的测试代码可以无成本遵循 karma 的编写规范，同时又只兼容你电脑上有的浏览器，那么 karma 就更轻巧

**Comment by atian25** [comment]
3x, 还有几个问题请教：
1. `totoro` 本地如何debug？ 能否类似`karma`那样可以用chrome dev tool 断点？
2. `browsers`在win8上无法打开chrome了。

**Comment by fool2fish** [comment]
1. 本地 debug 的话，你用浏览器直接打开你的测试页面就可以了啊，爱怎么调试怎么调试
2. browsers 打开浏览器的原理参考了 karma 的，所以要打不开就都打不开，主要这个功能有很强的平台限制性（当然，后面如果 karma 针对这个功能升级了也不一定，有段时间没关注 karma 了，呃）

**Comment by atian25** [comment]
第2个问题, 参见: https://github.com/totorojs/browsers/issues/48

本机karma是可以打开的, 怀疑是browsers的路径哪里出错

**Comment by valaxy** [comment]
恐怕karma不仅仅是单机模式吧？[官网](https://karma-runner.github.io/0.12/intro/how-it-works.html) 

> A browser can be captured either
> - **manually, by visiting the URL where the Karma server is listening** (typically http://localhost:9876/),
> - or automatically by letting Karma know which browsers to start when Karma is run (see browsers).
