### ISSUE TITLE
阿里巴巴内部还在用totoro来做测试吗?

### ISSUE THREAD

**Issue by valaxy** [totorojs/totoro#152]
已经好几个月没有动作了... 还在犹豫到底是用karma还是这个  如果你们有人找到了更合适的测试工具.. 拜托一定要分享给大家

**Comment by leoner** [comment]
目前我们内部还是用 totoro 来做测试的.

**Comment by fool2fish** [comment]
totoro 用于单元测试已经基本稳定了，内部运行表明服务的稳定性也很 ok
