### ISSUE TITLE
部署服务端代码

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro#16]
如题

**Comment by leoner** [comment]
完成部署，现在浏览器的分配情况如下:
87 为我们的 grid hub. 88，89，90 作为 node 
87 浏览器: ie9 和 firefox
88 浏览器: ie7 和 chrome
89 浏览器: ie8 和 safari
90 浏览器: ie6 和 opera

目前 firefox 由于兼容性的问题，目前版本为17. 其他除 ie 浏览器的版本都是最新版本。

queen 也已经在 87 上面部署好。可以通过 _._.*.87:9200 去连接测试。

**Comment by fool2fish** [comment]
所有的代码都放到 C:\totoro-server 里面，不分子目录

两个关联库（@leoner 均有权限）
- queen：https://github.com/fool2fish/queen
- events：https://github.com/fool2fish/events

**Comment by fool2fish** [comment]
注意：selenium 操作浏览器时，首先会打开一个端口随机的注册页面

目前服务器没有限定端口，否则这里会有问题

**Comment by fool2fish** [comment]
代码部署步骤已更新至 issue #11
