### ISSUE TITLE
选择事件模拟类库，移植和发布

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro#18]
如题

**Comment by leoner** [comment]
基本上完成迁移，详情参看 https://github.com/aralejs/event-simulate
剩余问题:
1.测试用例完善。
目前测试用例还在迁移中，测试用例主要是使用 yui3的。目前基本上迁移完成，主要是 dblclick 和 keydown 这两个事件还有点问题。后续在继续完善中。
2. 文档完善
这个接口相对比较简单，主要是参数比较多。
