### ISSUE TITLE
确认package.json 中测试框架和测试浏览器类型的配置

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro#21]
### 1、测试框架的配置

考虑过两种方式：
1. 所有的测试框架不转换成cmd模块，通过探测测试脚本来猜测使用了哪些测试框架
   - 好处：无需任何配置
   - 坏处：随着支持的框架增多，探测成本变高，难以维护
2. 所有的测试框架转换成cmd模块，mocha和jasmine这类测试套件比较特殊，不进行包装，但仍然发布到源上，开发者需要在 package.json 中指定依赖
   - 好处：市面主流的测试套件有限，可以根据指明的测试套件生成runner，其他的断言之类的工具通过require获得，无需关心
   - 坏处：开发者需要进行配置，多了一个工作步骤（有考虑过是否给定默认配置，但考虑到以后测试框架会不断演变，还会导致默认配置也需要变更，暂提供），但此步工作量较小。

**结论：**

使用方式2
### 2、指定要测试的浏览器或者运行环境的配置

这个先不提供配置，使用driver的默认配置即可

之前有讨论过用 engines,platform之类，仅参考

---

这些配置项在spm2中需要重新设置到 totoro 字段中

**Comment by fool2fish** [comment]
测试框架在 package.json 中的配置

```
{
    "xxx":{
        "mocha":"...",
        "expect.js":"...",
        "sinon.js":"..."，
        "event-simulate":"..."
    }
}
```

测试套件只允许出现一个，如 jasmine 和 mocha 就只允许出现一个，因为测试套件语法的特殊性，不能通过require引入，还需要在runner中进行一些额外的编码。

至于测试套件使用的是何种测试风格，bdd还是tdd，因为语法差异比较大，想不好应该提供什么配置项，从源码里抽取？

其他断言等相关工具按需要引入即可。

**Comment by lepture** [comment]
不要污染 devDependencies

**Comment by fool2fish** [comment]
工具提供默认配置：mocha + expect + sinon + event-simulate

暂不开放用户配置

**Comment by fool2fish** [comment]
3月13日，经过午饭和晚饭时间的讨论，和南伯、小高达成以下共识：
1. 对于测试脚本中的测试框架和非测试框架依赖，除了默认设定，需要提供配置项，一来是考虑到测试脚本中可能还会依赖一些普通的模块（正式环境不需要，又不是测试框架范畴的，比如模拟事件的 event-simulate），二来是即使我们可以统一所有的测试框架，但实际上也需要有地方指定要测试的浏览器。
2. 参考南伯的 [spm doc] 文档，在 spm2 中跟测试相关的配置大致如下：
   
   ```
   "spm": {
       "alias": {
           "class": "arale/class/1.0.0/class",
           "events": "arale/events/1.0.0/events"
       },
       "devAlias": {
           "mocha" "gallery/mocha/1.0.0/mocha",
           "expect" "gallery/expect/1.0.0/expect"
       },
       "engines": {
           "seajs": "seajs/seajs/1.2.0/sea.js"
       },
       "platforms": {
           "ie": [6, 7],
           "firefox": ["13"],
           "chrome": [20]
       },
       "platforms": ["ie/6", "chrome/20", "firefox"]
   }
   ```
   
   spm1中的配置相应放在 devDependencies 中
3. 所有用到的测试框架，都需要转换成 cmd 模块发布到源上，通过 require 使用。mocha 和 jasmine 也会发布到源上，但不会转换成 cmd 模块，作为特殊处理。
4. 由测试工具生成 runner 时，必须通过 sea_modules 使用本地依赖。另，所有依赖的模块，都通过 script 标签的形式加到 runner 头上。这样保证无论依赖的是否是 cmd 模块，都可以被使用。
5. arale 的模块 runner 的生成方案，可使用自己的工具，但需要遵守以上规范。稍后逐步调整。不强制约定 runner 生成位置。
6. 考虑将质量保障工具的命令集成到 spm 中，由于要兼容 spm 的两个版本，需要考虑下集成方式.

**Comment by lepture** [comment]
不是叫 `sea-modules` 么？怎么成了 `sea_modules` ？

**Comment by popomore** [comment]
第五点 arale 可能还是会用默认的方式，如果要用 puerh 就 require 使用。另外业务线以后也应该用 spm test，内置到 [spm-alipay-suite](https://github.com/spmjs/spm-alipay-suite) 中

**Comment by leoner** [comment]
那就没有 totoro test 了？ 就是需要挂载到 spm 中？

**Comment by popomore** [comment]
spm 这个包是给公司用的，totoro 还是可以自己发展

**Comment by leoner** [comment]
恩，明白！
