### ISSUE TITLE
解决 queen 同类浏览器重复运行单元测试的问题

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro#22]
如果有多个同样的浏览器可用，则只选择负载最小的一个发送任务

**Comment by leoner** [comment]
目前通过修改 queen 和 queen-remote 完成需求。
具体代码在 **https://github.com/leoner/queen** **https://github.com/leoner/queen-remote** 分支为 **totoro**
其中分别对这两个仓库改名为 totoro-queen 和 totoro-queen-remote.
目前代码已经部署到了 87 上面。
