### ISSUE TITLE
开源仓库的fork开发方案

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro#27]
见2楼

**Comment by anson0370** [comment]
以 queen 仓库为例：
1. fork 一份代码（假定为 queen2 ），queen2 的主干始终和queen的主干保持一致。
   
   > 如何保持主干的一致？
   > 1.  设置upstream remote：`git remote add upstream queen-url`
   > 2.  直接pull upstream remote：`git pull upstream master`
   > 
   > 查看变更后再合并更新
   > 1.  `git fetch upstream master`
   > 2.  `git diff master FETCH_HEAD`
   > 3.  `git merge FETCH_HEAD`
2. 新建 totoro 分支，有任何修改都在该分支上进行开发。
3. 从 queen2 的主干新建一个要 pr 的分支（假定为 pr-example），提取 totoro 分支中要 pr 的修改。
   
   > 1.  查看 totoro 分支要pr的提交： `git log` （假定hash为 e1ad54d）
   > 2.  切换到 pr-example 分支提取提交 `git cherry-pick e1ad54d`
4. 通过 pr-example 分支向 queen 的主干发起 pull request。如果被接受，则更新 queen2 的主干。
5. 删除 pr-example 分支。
   
   > 删除本地分支：`git branch -D pr-example`
   > 删除远端分支：`git push origin:pr-example`

---

cherry-pick 使用：
- 提取指定分支的 HEAD 提交：`git cherry-pick totoro`
- 提取指定分支的 HEAD 往前 n 个提交：`git cherry-pick totoro~n`
- 提取多个连续提交：`git cherry-pick A..B`，如 `git cherry-pick totoro~4 totoro` 会提取 totoro 分支上 HEAD 前4个和 HEAD 本身共5个 commit,`git cherry-pick e296145..a649050` 会提取 e296145 和 a649050 之间（含）的所有 commit。

更多用法请参考`git help cherry-pick`
