### ISSUE TITLE
指定浏览器进行测试

### ISSUE THREAD

**Issue by leoner** [totorojs/totoro#30]
### 使用方式

```
totoro test --browsers=ie,chrome,firefox
totoro test -b ie/6,ie/7
```

totoro 将会根据用户的输入匹配相应的浏览器进行测试。

> 目前还不支持针对某个操作系统的浏览器进行指定。
#### browsers 有效配置:
- ie ie6 ie7 ie8 ie9 ie10
- chrome chrome22
- firefox firefox19
- opera opera11
- safari safari6
1. 对于没有版本的都是模糊匹配，对于匹配上的浏览器都将进行测试。 
2. 针对某一具体的浏览器. 如果不匹配将没有浏览器被执行

**Comment by lepture** [comment]
上次和 @fool2fish 讨论了浏览器的写法，应该是

> "platforms": ["ie/6", "chrome/20", "firefox"]

所以应该是 -b ie/6,ie/7

http://docs.spmjs.org/en/package

**Comment by leoner** [comment]
已经支持下面写法

```
totoro test -b ie/6,ie/7
```

**Comment by lepture** [comment]
@leoner 我觉得原来的写法也可以保留，两种都可以工作。

**Comment by leoner** [comment]
恩，是的，都支持
