### ISSUE TITLE
thrill 关于扩展适配器的选择

### ISSUE THREAD

**Issue by leoner** [totorojs/totoro#31]
### 适配映射

```
totoro test --mapping=tests/runner.html,seajs
```

通过这个配置可以在指定的测试页面中添加 seajs 测试适配器。目前还没有想到更好的方式，暂时先通过这个方式啊。

在 thrill 模块中修改代码增加了下面这个配置:

```
adaptMapping: ['**.html', 'adapt']
```

通过这个来对指定页面添加适配器，适配器将会添加到 head 最后面。

**Comment by lifesinger** [comment]
能否这样：

```
totoro test --runner=tests/runner.html --adaptor=path/to/adator.js
```

adaptor 可以是默认的，比如 mocha、jasmine 等，也可以指向本地的一个文件
seajs 的适配器，应该放在 seajs 的仓库中才对

**Comment by lepture** [comment]
@lifesinger 这样的配置才对嘛。

**Comment by leoner** [comment]
恩，原来的配置确实不妥，今天早上和 @fool2fish 讨论的就是准备换成 **adaptor** 这个参数。
不过直接指定适配文件现在还有点问题，因为适配器需要在我们依赖的那个框架 thrill 打包编译后才能使用，所以还需要看看 thrill 这个框架中能否支持.

**目前可以支持下面几个参数:**
1. jamsine
2. mocha
3. qunit
4. yuitest
5. seajs

**Comment by leoner** [comment]
目前的方式为:

```
totoro test --adaptor=seajs
totoro test --runenr=tests/runner.html --adaptor=mocha
```

其中默认的 runner 就是 **tests/runner.html**

**Comment by lifesinger** [comment]
好
