### ISSUE TITLE
命令行参数

### ISSUE THREAD

**Issue by leoner** [totorojs/totoro#35]
## 命令行方式

totoro-test 目前充当了 server 和 client 双重角色。分别通过 **--server** 和 **--client** 来启动.默认是 **client**
### 启动服务

```
totoro-test
    --server
    --serverHost
    --serverPort
```
### 启动测试

```
totoro-test
    --runner
    --adapter
    --platforms
```
### 查看可用测试机器

```
totoro-test
    --list
```
## 配置方式
- 目前 totoro 统一成 totoro-config.js 配置，具体配置方式待定。

**Comment by fool2fish** [comment]
需联合考虑 package.json 的配置项，之前的讨论见 #21

**Comment by leoner** [comment]
命令行的方式已经完成。
