### ISSUE TITLE
产品参考

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro#4]
## 测试框架
- [expect.js](https://github.com/LearnBoost/expect.js/blob/master/README.md) - 断言
- [sinonjs](http://sinonjs.org/) - mock
- [mocha](http://visionmedia.github.com/mocha/) - 测试框架，任意断言，测试覆盖率，测试时间等
#### Selenium

这是一套和浏览器交互的解决方案，目前所有号称能搞定浏览器兼容性测试和功能测试的都是基于这个东东，阿里系的测试系统也一样。

更多移步 #6 
#### thrill
- 项目：https://github.com/turn/thrill
### 其他
- [uitest](http://uitest.taobao.net/tool/index.php) - 淘宝开发的专门用于 uitest 的工具
- [TDJS](http://www.letscodejavascript.com/) - 使用 socket.io 原理开发的测试工具，注意视频demo和原理讲解很棒！
- [dagger](https://github.com/NetEase/Dagger/wiki/Dagger) - 网易的封装了 selenium 的 ui 测试工具
- [ci.testling](http://ci.testling.com) - 和 browserling 配套的多浏览器单元测试工具，支持node，package.json 配置相关信息
- [saucelabs](https://saucelabs.com) - 支持多浏览器和操作系统的集成测试站点
  - 支持多语言，每个语言需下载对应的客户端，如 node:npm install wd
  - 需要在测试代码中指定浏览器
  - 定制的ui测试api
  - 开放了一些自定义事件，如：brower.on('command',fn)
  - 内网代码，需由it统一安装一个 sauce-connect-latest Java 包
  - 提供 rest api
- [phantomjs](http://phantomjs.org/) - 提供webkit环境的node库
- [CasperJS](http://casperjs.org/) - 基于phantamjs，提供了自己的断言，各种基础方法，包括浏览器端方法的测试框架
- [travis](https://travis-ci.org/) - 仅提供集成，测什么，怎么测完全自己来
### 无线
- [一淘无线测试](http://mtl.taobaotest.com/index)
## 基本不用看的
- [browserstack](http://www.browserstack.com/) - 类 saucelabs
- [browserling](https://browserling.com/) - 类 saucelabs
- [Buster.JS](http://docs.busterjs.org/en/latest/) - 非稳定版，会自动查找本机已安装的浏览器进行测试，提供自己的断言、桩、套件等。
- [jenkins](http://jenkins-ci.org/) - java写的，应该不是为前端服务的
- [Testacular](http://vojtajina.github.com/testacular/) - 几个人提到，最近官网改版，可以再看看

**Comment by leoner** [comment]
https://github.com/turn/thrill
https://github.com/turn/thrill/wiki/Comparison-to-Similar-Software

**Comment by lifesinger** [comment]
https://github.com/turn/thrill/wiki/Use

这就是我们想要做的呀，可以 fork 起来一起做，刚好大家可以练练英文写作。

**Comment by lifesinger** [comment]
Queen 也是这个组织做的，强大。Thrill 刚开始，我们现在就可以参与进去。

**Comment by leoner** [comment]
恩，现在这一类通过浏览器挂载的方式主要问题就是如果浏览器长时间不关闭的话，引起的性能问题，
那现在想我们是否可以结合 selenium 的 webdriver 来驱动浏览器的打开和关闭呢？这样就可以避免我们在手动去对浏览器进行注册了。

**Comment by lifesinger** [comment]
Thrill 里有说：

Queen offers some useful features:
- Automatic population of browsers through Selenium, BrowserStack or
  Sauce Labs.
- Automatic detection and restarting of unresponsive browsers.
- A monitoring page (in the above example, you could have gone to
  localhost:9000/monitor/ to see connected browsers and active jobs.

2013/1/28 hui.kang notifications@github.com

> 恩，现在这一类通过浏览器挂载的方式主要问题就是如果浏览器长时间不关闭的话，引起的性能问题，
> 那现在想我们是否可以结合 selenium 的 webdriver 来驱动浏览器的打开和关闭呢？这样就可以避免我们在手动去对浏览器进行注册了。
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/alipay/wd-qc-tools/issues/4#issuecomment-12774518.

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by leoner** [comment]
https://github.com/turn/queen/blob/stable/example/selenium/how-to-run-this-example.txt
