### ISSUE TITLE
测试适配器的扩展

### ISSUE THREAD

**Issue by leoner** [totorojs/totoro#41]
1. 适配器模块代码重构.
2. 支持用户自定义适配器

```
totoro-test --adapter=tests/adapter.js
```

**Comment by lifesinger** [comment]
赞，意味着 seajs 的 adapter 可以放到 seajs 自身的库了？

On Sat, Apr 13, 2013 at 11:37 PM, hui.kang notifications@github.com wrote:

> 1. 适配器模块代码重构.
> 2. 支持用户自定义适配器
> 
> totoro-test --adapter=tests/adapter.js
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro-test/issues/41
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by leoner** [comment]
现在 seajs 的适配器基本上的能用了，就差时间信息的输出了，明天在完善下，应该就可以提交了。

**Comment by leoner** [comment]
适配器检查不够完善。
