### ISSUE TITLE
ie9 测试不通过

### ISSUE THREAD

**Issue by leoner** [totorojs/totoro#48]
相关代码: static/constractor.html

```
  window.report = function(data){
 52                 console.info('report---', data.action)
 53                     reports.push(data)
 54    
 55                     if(data.action === 'end'){
 56                         var orderId = data.orderId
 57                         console.log('finish order: ' + orderId)
 58                         //setTimeout(function() {
 59                         removeOrder(orderId)
 60                         //}, 0);
 61                     }
 62                 }
```

如果 remoteOrder 异步执行，就是加上 setTimeout 程序没有问题.
下面是 ie9 下面的打印信息.
- 异步正确的日志
  ![52559D21-B306-4F56-9049-34CE0EF8E4E3](https://f.cloud.github.com/assets/546535/385811/e5cea5a6-a692-11e2-93d0-e60767d79fe4.jpg)
- 同步产生错误的日志
  ![19F0BC54-9F1A-4B2E-B5F4-89ECD020F30E](https://f.cloud.github.com/assets/546535/385814/fbddc94e-a692-11e2-90fd-b777f7efc7eb.jpg)

@fool2fish

**Comment by fool2fish** [comment]
see  @e82b55a

两个原因：
1. 在删除iframe后的很短时间内，iframe的测试脚本似乎还在运行，然后会发生错误，并报告这些错误（浏览器垃圾回收问题，没有特别好的办法解决。setTimeout 强制重新队列到最后运行）
2. 报告的数据是 JSON 格式的，并且有缓存，定时发送，所以当发生错误时，'end' 的数据会被修改，导致最后发送到服务端的数据错误。
