### ISSUE TITLE
增强日志功能

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro#49]
1. 日志格式可配置，可自动显示代码所在的文件，方法位置等
2. 确定日志规范
3. 帮助工具进行最基本的数据分析，如每天有多少 浏览器次 测试运行等

**Comment by leoner** [comment]
增加日志按周输出

**Comment by leoner** [comment]
日志文件默认存储在运行目录下面的 logs 目录中。
目前在命令行中输出规范为:

```
start server localhost:9999 (in server.js:Server.launchServer)
```

文件中输出规范为:

```
2013-04-22 05:15:41  start server localhost:9999 (in server.js:Server.launchServer)
```

> 由于我们日志是分级别输出的，所以在输出到文件的日志内容中没有体现出级别。
> 对于控制台我们是通过颜色来区分的。

**Comment by leoner** [comment]
增加日志文件输出开关，在测试的时候，可以允许用户关闭!
