### ISSUE TITLE
测试需求分析

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro#5]
![120110- ](https://f.cloud.github.com/assets/340282/67108/683b5716-5ee8-11e2-8d03-9b95d2f75f03.png)

**Comment by fool2fish** [comment]
## 测试系统结构图

![系统结构图](https://f.cloud.github.com/assets/340282/77390/d1c2a04c-6139-11e2-86f0-b6bf9e920a42.png)

**Comment by leoner** [comment]
http://ci.testling.com/

这个的使用方式我们可以参考下啊。

**Comment by lifesinger** [comment]
康辉推荐的这个不错，简直就是我们想要的
文档里提到的这个站点也挺有意思：http://testanything.org/  TAP 接口标准我们可以考虑直接拿来用

越发确定我们的方向是对的，这个需求很旺盛，关键要看我们能不能实现以及做好

2013/1/21 hui.kang notifications@github.com

> http://ci.testling.com/
> 
> 这个的使用方式我们可以参考下啊。
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/alipay/wd-qc-tools/issues/5#issuecomment-12481716.

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by fool2fish** [comment]
是滴，就是要这样的，这个和 browerling 是同一家，一个做单元测试，一个做回归测试。目前这些系统都是基于selenium，还没发现例外。康辉，期待你来杭州啊，selenium 各种 java，希望跟你一起研究下。

**Comment by leoner** [comment]
https://github.com/Camme/webdriverjs
https://github.com/LearnBoost/soda

记录下。

**Comment by popomore** [comment]
今天和 b2b 的聊，也提到了 webdriver
