### ISSUE TITLE
关于totoro下面相关模块全局配置文件风格和方式讨论

### ISSUE THREAD

**Issue by leoner** [totorojs/totoro#51]
**配置位置**
1. 全局   // 位置在 ~/.totorojs
2. 项目  (新增一个配置，或者配置在 package.json 中)
3. 是否还有其他类型的配置? (比如原来的源配置？)

**配置名称**
1. 我们全部都叫 totorojs.json or totorojs.js.或者其他一个统一的名称， 然后通过不同的字段来区分不同的模块。
2. 不同的模块有不同的配置文件。

**配置文件内容形式**
-  模块形式，就像 Gruntfile.js

```
module.exports = {
}
```
- 还是json 形式

```
{
     "clientCfg": {
        "serverHost": ''"
     },
     "serverCfg": {
        "serverPort": ""
     }
}
```

@fool2fish @hotoo @noahlu @lifesinger

**Comment by lifesinger** [comment]
## 配置位置
1. 用户：建议  `~/.totoro/`    不要加 js，与 `~/.spm/` 目录一样，配置文件为 `totororc`，格式为 ini 格式。
2. 项目：建议在项目根目录下，也是 ini 文件，名称为： `.totororc`
3. 不需要其他类型的配置，出发以后有需求，等以后再考虑

## 配置名称
1. 用户目录下的 `~/.totoro/totororc`   项目目录下的： `.totororc`
2. 是  ini 文件，通过不同字段区分，比如
   
   ```
   [totoro-test]
   ...
   
   [totoro-linter]
   ...
   ```

## 配置字段

ini 风格

totoro 理论上与 package.json 无关联，totoro 自身的配置，都存放在 totororc 文件中，只是 totoro 可以从 package.json 中读取需要的字段。

以上配置风格与 spm2 是一致的，南伯补充。

**Comment by lepture** [comment]
配置名称 `totoro-` 前缀可去掉。

**Comment by hotoo** [comment]
ini +1

**Comment by fool2fish** [comment]
```
module.exports = {
}
```

理由
1. 和代码风格统一
2. 不需要依赖额外的解析器
3. 可扩展性好

**Comment by lepture** [comment]
ini +1

**Comment by lifesinger** [comment]
ini +5

On Tue, Apr 23, 2013 at 3:43 PM, Hsiaoming Yang notifications@github.comwrote:

> ini +1
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro-test/issues/51#issuecomment-16843874
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by leoner** [comment]
大家都喜欢 ini 那就 ini 呀。

**Comment by leoner** [comment]
最新确定还是 json.

```
~/.totoro/config.json
```
