### ISSUE TITLE
参数 platforms 改为 browsers

### ISSUE THREAD

**Issue by leoner** [totorojs/totoro#56]

**Comment by lifesinger** [comment]
嗯，这样更清晰。

On Thu, May 2, 2013 at 9:08 PM, hui.kang notifications@github.com wrote:

> —
> Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro/issues/56
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香
