### ISSUE TITLE
将adapter移至server端

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro#57]
好处：
1. 减少更新客户端的需要
2. 支持 --runner=url 来测试线上的测试页面

**Comment by leoner** [comment]
到处理 --runner=url 处理线上测试页面的时候，在 server/order 中，由于接收到的 host 和 port 都是用户客户端的，所以如果用户指定的 runner 是线上的，
1. 在客户端把 host 和 port 替换成 runner 对应的？
2. 如果用户还指定了本地的 adapter的话，怎么处理？
3. 还是说客户端不发送 host 和 port 了，runner 和 adapter 都是标准的 url(keyword 除外)。 server 负责解析对应的 host 和 port

**Comment by fool2fish** [comment]
- runner 变成url，无clientHost 和clientPort
- adapter 为 url 或关键字，如 mocha
