### ISSUE TITLE
代码review和改进

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro#58]
- [x] 去 underscore
- [x] 重构参数预处理
- [x] 重构 utils.js

client和server
- [x] --platforms 改为 --browsers
- [x] 修改 OrderManager 和 LaborManager 的部分方法名
- [x] 统一order，list等方法名和socket名
- [x] 分离client和server
- [x] --adapter移至server

**Comment by lifesinger** [comment]
全部修改好后，再告诉我下，我再来看看，一起学习互进。

关于 「Manager 命名一般来说是坏味道」的说法，我重新 google 了下，可以参考：
- http://www.codinghorror.com/blog/2006/03/i-shall-call-it-somethingmanager.html

还有一篇各种争论：
- http://c2.com/cgi/wiki?DontNameClassesObjectManagerHandlerOrData

离开 OO 世界好久了，感觉上面的讨论也很久远。沉鱼看看，笑笑而过吧。

**Comment by lifesinger** [comment]
我还没 review 呢，保留 open 先。
