### ISSUE TITLE
客户端 http 服务外网无法访问

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro#64]
### 问题描述

--runner 为本地文件时， client 会起一个 http 服务，用于让 server 访问 runner，但公共服务访问不了局域网的 client http server

通用的解决方案是在局域网的路由上安装一个代理，如 selemium

但这样的解决方案过于笨重，需要寻求更轻量的解决方案
### 设想的方案

服务端处理流程

![http-and-socket-proxy](https://f.cloud.github.com/assets/340282/767470/e8a8f0fc-e881-11e2-87f0-807446383f9f.jpg)

这样的设计下，系统是具有弹性的，当服务可直接访问 runner 的时候，就按原来的方式（http 代理），当服务不可直接访问 runner 的时候，就用 socket 代理的方案
#### 关键步骤：proxyType 判断
1. 何时判断
   - 属于一个 order 或者一个 cache 的第一个请求，一定是 runner，只需要在 runner 请求的时候进行一次判断即可
2. 如何判断
   - 发送 http(s) head 请求，能访问则为 httpProxy，否则为 socketProxy（注意：这里有异步操作）
3. 效率如何
   - 对于局域网的部署和使用没有任何影响
   - 至于 socketProxy 的效率如何，有待后续拿到数据
### socket 的效率

见：https://github.com/totorojs/totoro-server/commit/5046772b82ed51e2a5a6ee2f8d3342d95a432a6d

目前来看，单个 socket 和 http 的效率相差 2-3 倍，完全在可接收的范围内，后续还有优化余地。由此可见，该设想可行。

**Comment by leoner** [comment]
目前的方案是通过客户端和服务器建立 socket 链接，然后服务器端通过 socket 的方式从用户这里读取数据。

**Comment by leoner** [comment]
基本上结构出来了，但是遇到了一个比较严重的问题，就是从客户端 emit 到服务器的 buffer 内容，在服务器端解码后的内容为

```
str--------> 60,33,68,79,67,84,89,80,69,32,104,116,109,108,62,10,60,104,116,109,108,62,10,32,32,60,104,101,97,100,62,10,32,32,32,32,60,109,101,116,97,32,99,104,97,114,115,101,116,61,34,117,116,102,45,56,34,62,10,32,32,32,32,60,109,101,116,97,32,110,97,109,101,61,34,118,105,101,119,112,111,114,116,34,32,99,111,110,116,101,110,116,61,34,119,105,100,116,104,61,100,101,118,105,99,101,45,119,105,100,116,104,44,3
```

应该是传输的时候 buffer数组被转成字符串了，晚上在研究下看看能不能正确的反转过来.

**Comment by leoner** [comment]
目前已经初步完成一个版本了，但是现在就是什么情况来使用 socket 传输，还是说我们压根就是直接通过 socket 传输，不通过 http 的方式了。

**Comment by leoner** [comment]
现在的处理逻辑还是本地启动一个 server, 然后通过 socket 接收从服务器端传递过来 request 的信息，然后去请求本地的 http 服务，然后在把相应的 res 信息 emit 给服务器。

本地的 server 还是必须的，因为还是牵扯到 http 请求编码啥的，如果我们直接通过文件读取还是有点问题的。

**Comment by leoner** [comment]
现在有一个问题，就是测试 seajs 的时候，如果测试浏览器中包括多个浏览器，那么 ie6.0 浏览器经常就会挂掉。错误提示为

```
R6025 pure virtual function call
```

 但这个错误也不是百分百重现，如果再次出错，尝试用这个解决下
http://support.microsoft.com/kb/925418

**Comment by leoner** [comment]
目前就是用我们自己的服务器是没有问题的，只有用一个外网的服务器会出现此问题，而且当只有一个 ie6 的时候，也没有问题，不知道是不是国外服务器网络的问题？

**Comment by lifesinger** [comment]
现阶段是否可以不支持外网？让局域网的部署变得方便就行。最近跟 hax 还有微软的一个同学聊过，他们更期待能有更方便的局域网部署方案（文档），能方便部署在自己公司，这样：
1. 不用考虑网速问题，外网速度是个考虑点，内网会快很多。
2. 不用担心安全问题，有些测试代码，放到外网有顾虑。

因此我的想法，外网访问的问题可以暂缓，即便我们可以申请得到阿里云的资源，后期维护，并发等等，也都存在问题，会消耗掉我们大部分时间。现阶段还是聚焦在测试工具本身的完善上比较好。

阿里云的资源，我也去联系了下，预算要明年了。我会记下来，明年去申请。

**Comment by lifesinger** [comment]
IE6 的问题有进展没？有没有定位到具体原因？

**Comment by leoner** [comment]
目前 xbox 的测试还是能把ie6 搞挂，还没有找到原因啊。

**Comment by lifesinger** [comment]
@leoner xbox 是否有在 dom ready 之前插入 dom 的操作？我怀疑还是这个原因导致。

**Comment by leoner** [comment]
恩，在之前直接通过 ie6 访问也是会直接挂掉的，经过测试用例的修改，直接访问是没有问题了。但是通过 totoro 还是会挂。 明天测试下，看看通过 iframe 访问 xbox 的测试用例有没有问题。

**Comment by leoner** [comment]
iframe 的方式也是会挂的，但是不是立马挂掉，而是等了一会时间后，会弹出那个 R6025 pure virtual function call 的错误框

**Comment by leoner** [comment]
但是也不是百分百重现, 但是10次应该有5次能出现这个错误

**Comment by lifesinger** [comment]
xbox 里是否有调用 iframe-shim？将 xbox 的测试代码，放到 dom ready 里试试。

**Comment by fool2fish** [comment]
测试工具本身还需要完善啥？0.3.0 的功能没啥所谓本身需要完善的功能啊，连 coverage 都不是

**Comment by lifesinger** [comment]
CI

On Mon, Jul 8, 2013 at 11:46 AM, fool2fish notifications@github.com wrote:

> 测试工具本身还需要完善啥？0.3.0 的功能没啥所谓本身需要完善的功能啊，连 coverage 都不是
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro/issues/64#issuecomment-20584386
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by fool2fish** [comment]
参考之一：https://github.com/turn/json-over-tcp
