### ISSUE TITLE
通过 --config 参数进行全局配置

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro#68]
如题，类似 git config

这样用户不用关心平台，直接设置即可

**Comment by fool2fish** [comment]
设置

totoro --config --server-host=0.0.0.0 --cfg-name=cfg-value

删除

totoro --config --server-host

读取

totoro --config

用户可能唯一需要进行全局配置的就是这个选项，看起来就没有必要让用户根据操作系统去找全局配置文件了，用起来页比较简单

**Comment by leoner** [comment]
我们常用的参数就是这两个，而且一般参数的内容也不经常变化，所以这种方式挺好的，那我们就支持下吧。

**Comment by fool2fish** [comment]
记得改下 readme 里相应的部分啊
