### ISSUE TITLE
【求助】首次配置totoro环境测试官方demo返回no active browser

### ISSUE THREAD

**Issue by alvinhui** [totorojs/totoro#71]
### 软件背景
1. **操作系统**：Linux mint 14 / 内核版本： 3.9.0
2. **浏览器信息**：Chrome 27.0.1453.93
3. **totoro版本**：0.2.2
4. **totoro-server版本**：0.2.2
5. **browsers版本**：0.4.6
### 重现步骤
1. **安装totoro**：进入 https://github.com/totorojs/totoro 下载zip方式获取项目，解压，进入解压后文件夹，运行sudo npm install -g

``` shell
$ unzip totoro-master.zip
$ cd totoro-master
$ sudo npm install -g
```
1. **安装totoro-server**：git clone方式获取项目，解压，进入解压后文件夹，运行sudo npm install -g

``` shell
$ git clone git@github.com:totorojs/totoro.git
$ cd totoro
$ sudo npm install -g
```
1. **安装browsers**：npm install browsers -g

``` shell
$ npm install browsers -g
```
1. **开启totoro-server**：

``` shell
$ totoro-server
```
1. **开启browsers**：

``` shell
$ browsers
```
1. **运行测试**：

``` shell
.../totoro/examples/simple $ totoro --server-host=192.168.11.6 --verbose=true --list
```
### 期待值与真实结果
1. **期待结果应是官方示例的结果图**：
   ![totoro](https://f.cloud.github.com/assets/340282/476620/b326ddb6-b7c3-11e2-94b7-4828df877218.png)
2. **实际结果返回请看下图**：
   ![totoro](http://alvinxu.com/download/Screenshot%20from%202013-06-08%2015:55:04.png)

首次使用，请大侠们轻拍。

**Comment by fool2fish** [comment]
1、--list 用于显示可用的测试机机器，当该参数存在的时候不运行单元测试
2、建议先不要使用 browsers，手工打开浏览器，访问 {{your ip}}:9999，看看测试是否能正常运行
3、看截图似乎是没有找到浏览器，目前明确能跑的是mac和win系统，linux还未测过。你的浏览器是按默认路径安装？

**Comment by alvinhui** [comment]
感谢回复。

经我这边的本地测试，应该是可以跑linux系统的。在我第二次重试后已经可以得到期待中的结果。（实现步骤和第一次测试时一模一样）

我的浏览器安装都是默认路径的。比较奇怪的是只能检测到Chrmoe检测不到Firefox。

有个疑问是，为什么在browsers配置里没提供参数来设置浏览器路径？（还是说有但我没找着？）

**Comment by leoner** [comment]
@alvinhui 配置没有开放出去，下一步会支持不同操作系统下面的浏览器路径配置.
