### ISSUE TITLE
读取 package.json 中的 browsers 信息

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro#72]
如题

**Comment by leoner** [comment]
没有太明白，在 package.json 中我们支持配置 browsers ?

**Comment by fool2fish** [comment]
嗯，因为如果 server-host 和 server-port 通过 config 来配置的话，理论上就只有 browsers 需要配置了
不过这个配置的格式如果想放到 package 中还需要看下业界的做法，在周会上讨论下先

**Comment by lifesinger** [comment]
一般不用配 browsers 吧？

**Comment by leoner** [comment]
karma 也是通过其他配置文件的，那我们是不是如果用户需要指定浏览器的话，也是通过我们的 totoro-config.js 来完成？就不污染 package.json 了。

**Comment by lifesinger** [comment]
我比较赞同 totoro-config.js 的方案，不污染 package.json

2013/7/8 hui notifications@github.com

> karma 也是通过其他配置文件的，那我们是不是如果用户需要指定浏览器的话，也是通过我们的 totoro-config.js 来完成？就不污染
> package.json 了。
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro/issues/72#issuecomment-20586930
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by fool2fish** [comment]
理论上是要配置 browsers 的，标记自己的代码是兼容哪些浏览器的，这个信息属于 package.json 也正常（当然现在还没有）

totoro-config.js 这个不变，只是说如果没有配置文件的时候，多去查看下 package.json

如果不配的话，就按服务端现有的浏览器来跑

**Comment by fool2fish** [comment]
2013-07-11 周会讨论了下，package 暂时不加（实际上也不会有人设置 totoro-config.js）
那么测试完全依赖于服务端已有的浏览器类型进行自动分配，这是一个潜在的小风险点
