### ISSUE TITLE
totoro list 显示更多信息

### ISSUE THREAD

**Issue by afc163** [totorojs/totoro#75]
显示所有可测试的浏览器和操作系统信息，包括浏览器小版本号和操作系统小版本号。

**Comment by leoner** [comment]
```
    Chrome 27.0.1453 / Mac OS X 10.8.4 [2]
    Firefox 22.0.0 / Mac OS X 10.8 [1]
    IE 6.0.0 / Windows XP [1]
```

目前就 win 下面无法显示浏览器的小版本号和操作系统的小版本号，因为

```
Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)
Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C)
```

没有足够的信息可以获取呀。

**Comment by lifesinger** [comment]
Windows NT 有版本号呀
浏览器到 4.0 和 5.0 就够了

On Thu, Jul 4, 2013 at 4:06 PM, hui notifications@github.com wrote:

> ```
> Chrome 27.0.1453 / Mac OS X 10.8.4 [2]
> Firefox 22.0.0 / Mac OS X 10.8 [1]
> IE 6.0.0 / Windows XP [1]
> ```
> 
> 目前就 win 下面无法显示浏览器的小版本号和操作系统的小版本号，因为
> 
> Mozilla/4.0 (compatible; MSIE 6.0; Windows NT 5.1; SV1)
> Mozilla/5.0 (compatible; MSIE 10.0; Windows NT 6.1; WOW64; Trident/6.0; SLCC2; .NET CLR 2.0.50727; .NET CLR 3.5.30729; .NET CLR 3.0.30729; .NET4.0C)
> 
> 没有足够的信息可以获取呀。
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro/issues/75#issuecomment-20464180
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by afc163** [comment]
ie 系列的小版本号，有意义。

**Comment by leoner** [comment]
收集了下 ie6 的小版本，如果对我们有意义的话，估计又要在崩溃一次了呀。

```
   6.00.2462.0000   Internet Explorer 6 Public Preview (Beta)
   6.00.2479.0006   Internet Explorer 6 Public Preview (Beta) Refresh
   6.00.2600.0000   Internet Explorer 6 (Windows XP)
   6.00.2800.1106   Internet Explorer 6 Service Pack 1 (Windows XP SP1)
   6.00.2900.2180   Internet Explorer 6 for Windows XP SP2
   6.00.2900.5512   Internet Explorer 6 for Windows XP SP3
   6.00.3663.0000   Internet Explorer 6 for Windows Server 2003 RC1 
   6.00.3718.0000   Internet Explorer 6 for Windows Server 2003 RC2
   6.00.3790.0000   Internet Explorer 6 for Windows Server 2003 (released)
   6.00.3790.1830   Internet Explorer 6 for Windows Server 2003 SP1 and Windows XP x64
   6.00.3790.3959   Internet Explorer 6 SP2 for Windows Server 2003 SP1 and Windows XP x64 
```

**Comment by hotoo** [comment]
崩溃了~

**Comment by lifesinger** [comment]
没必要吧
什么 bug 要这么精准的信息？
个人觉得拿到这些小版本，对我们也没什么帮助。

On Fri, Jul 5, 2013 at 10:41 AM, 闲耘(tm) notifications@github.com wrote:

> 崩溃了~
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro/issues/75#issuecomment-20499210
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by fool2fish** [comment]
ie不支持小版本号，翻了下issue，这个需求好像是从xbox出来的？即便我们提供了所有小版本的ie，最后测试也只会告诉用户那个版本的出问题了，排查问题的时候还是需要自己打开对应的ie去看，投入产出比太低，而且是非典型需求

**Comment by afc163** [comment]
没有理解我的意思，不是需要 totoro 提供所有小版本号的测试机器，而是遇到一些诡异问题后，希望看一下对应浏览器的小版本号帮助排查。现在没有办法登录到测试机上自己去查看，只能由工具把这个信息给出来。

**Comment by fool2fish** [comment]
只是显示小版本技术上问题是不大的，但需要考虑的是：
1. 这是不是一个大多数人都需要的功能，或者说除了 xbox 还有其他需求么？
2. 原本的 list 信息有分组的，后面跟了有多少个同类浏览器在跑的数字，如果 ie 系也弄小版本号，那分组浏览器一多，看起来就很头大了

**Comment by lifesinger** [comment]
这个我觉得可以先关闭吧，等第三次再遇到类似需求时，再考虑。

2013/7/8 fool2fish notifications@github.com

> 只是显示小版本技术上问题是不大的，但需要考虑的是：
> 1. 这是不是一个大多数人都需要的功能，或者说除了 xbox 还有其他需求么？
> 2. 原本的 list 信息有分组的，后面跟了有多少个同类浏览器在跑的数字，如果 ie 系也弄小版本号，那分组浏览器一多，看起来就很头大了
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro/issues/75#issuecomment-20589896
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by afc163** [comment]
小版本号可以不参与分组啊。

另外，显示操作系统信息目前也不是什么大多数人都需要的需求吧。显示出来只是为了数据的完备性。

**Comment by fool2fish** [comment]
不参与分组，怎么显示？
