### ISSUE TITLE
totoro config 异常

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro#76]
totoro config --server-host=0.0.0.0 输出了版本号
其他两个 config 功能没有测

**Comment by fool2fish** [comment]
1. `totoro config` 时，如果没有任何配置，应该输出一个 cyan 颜色的提示，告诉用户当前没有任何全局配置
2. `totoro config --server-host` 为删除 --server-host 全局配置，而非显示指定的项的全局配置，查看全局配置总是由 `totoro config` 来完成，且总显示全部的全局配置，选项少，没必要指定
3. commander 会自动把 --server-host 转换成 --server-host=true，要处理下，如果确实没有传值，则认为传入了一个非真值，只要是传入非真值的，就删除
4. updateGlobalCfg() 时，如果全局配置文件不存在则要先创建

**Comment by leoner** [comment]
1. `totoro config --server-host=""` 当用户明确指定某个配置为空时，删除此配置.
