### ISSUE TITLE
关于 ie6 浏览器崩溃的问题

### ISSUE THREAD

**Issue by leoner** [totorojs/totoro#77]
上周到现在陆续发现 ie6 莫名的挂掉, 挂掉主要是产生下面两个错误:
![ce38be19c717ca4c7c4462e21c6cc0a4](https://f.cloud.github.com/assets/546535/766671/4409527e-e86a-11e2-9116-a97cd4460be1.png)
![64899ce54dc4c68c8a0634b7c8dafca4](https://f.cloud.github.com/assets/546535/766678/6b00344c-e86a-11e2-9e5a-f141a336ab4d.png)

目前产生问题主要有以下几个原因,供参考:
### 代码错误

totoro 在进行 socket 改造的时候, runner.html 的装饰方法执行了多次, 导致了在同时运行多个浏览器的时候, ie6 由于执行的比较慢,所以在 ie6 请求的 runner.html 实际被装饰了2次,结果造成了 ie6 运行了一个不正确的页面,从而产生错误.

> https://github.com/totorojs/totoro-server/commit/014e99e1ac5e3a2f343da3a333637e60e4a3a323
### seajs 运行错误

由于运行了错误的 seajs 测试页面,也会导致浏览器挂掉

```
http://seajs.org/tests/runner.html (错误)
http://seajs.github.io/seajs/tests/runner.html(正确) 
```
### xbox 运行错误

基本上都是由于 iframe xbox 指定的 url 导致的原因. 有些可能是由于页面禁止 iframe, 有些是由于页面内存泄露,控件等问题.

**总的原因就是页面的不正确,触发了 ie6 的某些问题,导致挂掉**

**Comment by fool2fish** [comment]
seajs 导致浏览器崩溃的原因是在ie下运行太快了，调慢在ie下运行的速度即可

**Comment by lifesinger** [comment]
seajs 导致浏览器崩溃的原因：
1. 线上地址必须是 http://seajs.github.io/seajs/tests/runner.html  不能用 com 那个，否则插件相关的测试用例会失败。
2. 如果是线下测试，则除了 clone seajs 还需要 clone seajs/xxx 库，保证插件的测试用例也都能跑。
3. 沉鱼说的那个也是个问题，调慢会更稳健一些。
