### ISSUE TITLE
收集测试模块的 repo 信息

### ISSUE THREAD

**Issue by leoner** [totorojs/totoro#79]
分为两种情况:
1. 本地项目直接读取 package.json
2. runner 为 url 的话, 需要进行额外的处理
    - 探测到 package.json 读取相关信息
    - 如果没有探测到, 只要使用 runner 的 url

**Comment by fool2fish** [comment]
完整的判断逻辑：
- 1 runner 是 dir
  - 1.1 查找 package.json
  - 1.2 查找 .git 的信息
  - 1.3 查找 .svn 的信息
- 2 runner 是 url
  - 2.2 查找 package.json 的信息
  - 2.3 指定 runner 的 url 为 repo（这里有点语义上的问题）

简单考虑，可以先只实现 1.1 和 2.3 两个

**Comment by fool2fish** [comment]
server 端要跟着处理，作为 order 的属性放进去

**Comment by cyjake** [comment]
这个收集了是做什么用的？
