### ISSUE TITLE
命令行参数

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro#8]
1. totoro test
   - 命令可以在模块根目录或者 test/tests 文件夹中运行
   - 会自动找到 test/tests 目录中的 runner.html 开始测试
   - 如果没有找到 runner.html，则根据默认测试框架(mocha, expect.js, sinon, event-simulate)生成 runner.html。也就是说，如果默认的测试框架无法满足需求，则需要开发者自己拼写 runner。
2. - r --run path/to/runner.html
     指定要运行的runner，这样使用非指定测试框架，或者存放在非指定位置的runner，就可以运行
3. -f --force
   强制重新生成 runner

**Comment by leoner** [comment]
```
npm install totoro -g
```

目前版本为  0.0.2

```
totoro test
totoro help test
totoro test -r path/to/runner.html
totoro test -f
```
