### ISSUE TITLE
客户端 list 子命令外网无法访问

### ISSUE THREAD

**Issue by leoner** [totorojs/totoro#86]
list 是否直接通过 socket 来进行信息传输？ 毕竟这个内容不是很多。

**Comment by fool2fish** [comment]
list 是客户端向服务端发的 http 请求啊，如果无法访问那是因为服务本身不对外开放吧？

**Comment by leoner** [comment]
哦, 忘记了. 不知道为啥用 vpn 访问不了. 那应该不是这个原因. 可能还是网络的问题.
