### ISSUE TITLE
安装的时候出错了

### ISSUE THREAD

**Issue by despairlin** [totorojs/totoro#89]
执行sudo npm install totoro -g的时候出现了“ Error: version not found: 0.1.3 : totoro-common/0.1.3”这个，请问是什么问题？

**Comment by fool2fish** [comment]
totoro 和 totoro-server 都依赖 totoro-common 这个模块，最新的开发代码，totoro 依赖的是 还未发布的 totoro-common 0.1.3，所以如果现在直接从源码安装会找不到这个模块

建议：
1. 直接通过 npm 安装 totoro，上周刚发过 0.3.0 的新版本，已经是最新了
2. 如果非常想体验开发中的代码，请使用 `npm link` 来链接 totoro-common（这个操作有点繁琐，如不知道的话就不要用好了）

另：

非常感谢你的反馈，为了保证开发中的版本也随时可用，我会尽快完成 totoro-common 0.1.3 的测试，在下周五之前发布上线
