### ISSUE TITLE
整体技术方案

### ISSUE THREAD

**Issue by fool2fish** [totorojs/totoro#9]
![ ](https://f.cloud.github.com/assets/340282/252168/9275ccf4-8b8a-11e2-815a-a1a161c944d3.png)

**Comment by fool2fish** [comment]
代码划分

## server
1. 根据用户请求信息，负责收集测试需要的内容(测试代码，或者项目模块等)
2. 根据用户提供的信息自动生成 driver 脚本。
   1. 脚本需要负责从测试页面中拿到数据。
3. 执行脚本，驱动 selenium。然后收集脚本执行结果，并汇总
4. 返回信息到客户端

## client
1. 解析配置
2. 把 server 需要的信息传递给 server(tcp ? 还是 git clone ?)
3. 等待服务器通知
4. 显示服务测试信息。

**Comment by leoner** [comment]
https://github.com/sebv/node-wd-sync 可以看下这个。 把 wd 包装了下，支持同步的调用. 我们可以看看是不是可以基于他再进一步的改进呀！

```
sync( function() {

  console.log("server status:", browser.status());
  browser.init( { browserName: 'firefox'} );
  console.log("session capabilities:", browser.sessionCapabilities());

  browser.get("http://google.com");
  console.log(browser.title());

  var queryField = browser.elementByName('q');
  browser.type(queryField, "Hello World");
  browser.type(queryField, "\n");

  browser.setWaitTimeout(3000);
  browser.elementByCss('#ires'); // waiting for new page to load
  console.log(browser.title());

  console.log(browser.elementByNameIfExists('not_exists')); // undefined
  browser.quit();
});
```

**Comment by fool2fish** [comment]
已准备ppt，先在组内进行分享，达成共识

持续完善ppt，稍后可用于集团内技术交流

运作一段时间后，可能需要寻找运维等技术支持
