### ISSUE TITLE
测试用例如果是 gbk 编码导致 totoro 运行错误

### ISSUE THREAD

**Issue by leoner** [totorojs/totoro#91]
场景:
- spec 文件为 gbk 编码
- 然后中间包含 中文 `describe('工具函数', function() {`
- 浏览器为 ie9, safari

现象:
- 浏览器端会导致 socket disconnect. 然后会继续 connect
- 服务器会导致重复执行 labor, 进入死循环.

解决办法:
- 在 runner.html 中引入的 gbk 的文件一定要写上 `charset="gbk"`

需要后续跟踪:
- 为啥文件编码会导致 socket 断掉呢?
- 为啥会重复执行 labor? 因为感觉测试用例还是执行完毕的状态?

**Comment by leoner** [comment]
现在的解决办法就是在 runner.html 中添加

```
seajs.config({
      charset: 'gbk'
})
```

但是问题是这个工作是不是需要totoro 来解决?

**Comment by fool2fish** [comment]
添加服务端执行限制，如果一个指定浏览器执行超过 n 次不能正常完成，就停止在该类浏览器中测试，并报错。
