### ISSUE TITLE
测试覆盖率提示信息增加未覆盖到行的提示

### ISSUE THREAD

**Issue by leoner** [totorojs/totoro#92]
比如

```
Passed all of 19 tests in 4956ms (coverage 92.11%)
```

那么表明你源代码中有些地方未覆盖到. 为了方便用户进一步有针对性的完善测试用例,我们可以对源代码中那些行没有覆盖到进行提示. 但是由于这个信息的获取是从浏览器执行测试的时候拿到的,如果完整显示会造成数据传输过大.  所以目前打算有条件的显示(只有覆盖率到达90%的时候并且`--verbose`)并且精简的信息:

```
picker.js [10, 11, 12, 21, 34]  // 表明 picker.js 中的 10, 11, 12.. 行的代码没有覆盖到.
contactsList.js [20, 34, 56] 
```

现在有两个问题:
- 如何显示的更友好? 
- 触发显示的条件?

大家有啥好的想法?

**Comment by fool2fish** [comment]
1. 先确定大家是否需要这种详细的提醒
2. 在第一回答是肯定的前提下再关注如何显示的更友好啊，个人觉得最好运行一个保真的demo截图，光示范代码看不出来东西

这两个问题都解决的话，我觉得在一定的阈值前提下，--verbose 倒不一定必须

**Comment by popomore** [comment]
可以通过 coverage 生成一个临时页面，然后提供链接。

arale 是通过 spm test 在本地生成一个 html，但只有 chrome，totoro 是按浏览器输出信息还是整合的信息。

**Comment by leoner** [comment]
![snip20130819_1](https://f.cloud.github.com/assets/546535/985094/c5b3ec18-08b2-11e3-8a43-81836375401e.png)

**Comment by leoner** [comment]
目前的效果图

**Comment by afc163** [comment]
提供覆盖率页面链接。

**Comment by lepture** [comment]
https://github.com/lepture/coverage-render

![screen shot 2013-08-19 at 5 50 30 pm](https://f.cloud.github.com/assets/290496/985153/d395a478-08b4-11e3-87cc-90776d0f0efb.png)

**Comment by leoner** [comment]
目前这个只是在终端提示方案! 主要目的还是用户可以简单直观的获取那些代码没有覆盖到, 可以有针对性的补充测试用例. 后续会有一个完善的覆盖率页面, 来显示代码行执行次数等完整的信息呀.

**Comment by leoner** [comment]
https://coveralls.io/files/23315469
http://10.232.102.134:1984/alipay-js/request/coverage.html 

@popomore  提供的两个参考页面.

**Comment by lifesinger** [comment]
我觉得不用这么详细的信息，没有 95% 以上时，数值用黄色显示就好。

比如小于  80%  用红色
80 - 94% 用黄色
95% 以上用绿色

有颜色区分，就让人有追求了。

On Tue, Aug 20, 2013 at 9:51 AM, hui notifications@github.com wrote:

> https://coveralls.io/files/23315469
> http://10.232.102.134:1984/alipay-js/request/coverage.html
> 
> @popomore https://github.com/popomore 提供的两个参考页面.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro/issues/92#issuecomment-22917621
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by lifesinger** [comment]
终端保持简单

完善的覆盖率页面详细即可

2013/8/23 Frank Wang lifesinger@gmail.com

> 我觉得不用这么详细的信息，没有 95% 以上时，数值用黄色显示就好。
> 
> 比如小于  80%  用红色
> 80 - 94% 用黄色
> 95% 以上用绿色
> 
> 有颜色区分，就让人有追求了。
> 
> On Tue, Aug 20, 2013 at 9:51 AM, hui notifications@github.com wrote:
> 
> > https://coveralls.io/files/23315469
> > http://10.232.102.134:1984/alipay-js/request/coverage.html
> > 
> > @popomore https://github.com/popomore 提供的两个参考页面.
> > 
> > —
> > Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro/issues/92#issuecomment-22917621
> > .
> 
> ## 
> 
> 王保平 / 玉伯（射雕）
> 送人玫瑰手有余香

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by leoner** [comment]
这个需求的初衷只是想增加一种简单的方式, 可以让使用者快速的定位到未覆盖的行. 具体的详细页面后续会提供的.
目前折中了下显示方案:
- 服务器只会在 60% 的时候收集详细信息
- 客户端只会在 `--verbose` 的情况下才会输出此信息.

**Comment by lifesinger** [comment]
这样的话，要不简单点吧：

> 只在覆盖率大于等于 95% 的时候收集并显示未覆盖信息

**Comment by leoner** [comment]
现在收集数据感觉应该对性能影响不大, 因为这个数据量不是很大.因为就是行号. 所以我现在是在 60% 的时候就去收集数据.

然后自动显示的这个标准很难确定, 项目大小的不同, 这个值的含义是不同的, 对于一个比较大的项目, 当到了 80% 的时候, 就很难定位那些没有覆盖到了.  所以通过 `--verbose` 主动控制覆盖率的显示的话, 用户可以灵活的去掌握呀.

**Comment by lifesinger** [comment]
我还是倾向于这个方案：

> 具体的详细页面后续会提供的

客户端感觉真没必要啊，还得自己去数第几行，很不直观。

**Comment by leoner** [comment]
目前通过 --verbose 参数来控制信息的显示和收集.  如果用户添加`--verbose`那么就会去收集覆盖率相信信息, 并进行显示.
