### ISSUE TITLE
是否提供一个接口，可输出 log 信息

### ISSUE THREAD

**Issue by lifesinger** [totorojs/totoro#94]
通过 totoro 测试时，有时想看看某些值在各个浏览器下输出结果，是否可以

在 spec 里写

```
totoro.log('xxxx')
```

然后在客户端就可以看到相关信息？

好处是，如果有这么一个方法，对调试会非常有利，可以减少不少开虚拟机的需求。

**Comment by leoner** [comment]
确实是, 我现在也是在专门调试某个问题的时候, 也是只能打开浏览器, 盯着控制台呀. 
输出倒是应该能实现, 但是由于测试多个浏览器的时候, 需要看看如何吧这些信息输出:
- 实时?
- 在测试完成后, 输出到汇总那里?

**Comment by popomore** [comment]
话说调试用网页呀，totoro 多慢。

**Comment by lifesinger** [comment]
@leoner 在测试完成后，汇总输出就好。实时有点麻烦吧？

@popomore 单个测试用例时，totoro 很快的。如果有 totoro.log 方法，则不少时候，不用开虚拟机就可以调试了。比如今天周会我分享的那个 IE10 cache bug. 最后的调试办法就是不断打 console.log

**Comment by leoner** [comment]
> 话说调试用网页呀，totoro 多慢。

我们会努力提升速度的呀.

**Comment by leoner** [comment]
```

ie 6.0 / windows XP  abc

ie 6.0 / windows XP  eeee
.
safari 7.0 / macosx 10.9  abc

safari 7.0 / macosx 10.9  eeee
.
chrome 28.0.1500.95 / macosx 10.9.0 /tests/example-spec.js:7:20 abc

chrome 28.0.1500.95 / macosx 10.9.0 /src/simple.js:39:16 eeee
.

  chrome 28.0.1500.95 / macosx 10.9.0
  Passed all of 1 tests in 589ms (coverage 100.00%)

  ie 6.0 / windows XP
  Passed all of 1 tests in 20ms (coverage 100.00%)

  safari 7.0 / macosx 10.9
  Passed all of 1 tests in 31ms (coverage 100.00%)

===============================
  Passed on all of 3 browsers
===============================
```

这样显示行? 如果到最后统一显示的话, 更加麻烦. 改动的地方比较多. 
然后如果是 chrome 可以稍带把具体日志的行号给探测出来.

**Comment by lifesinger** [comment]
挺好的，赞速度，明天公司试用下。

**Comment by leoner** [comment]
这个正式的估计要等到下周才能发, 明天会把最新的功能发布到另外一台机器上. 好了通知你呀.

**Comment by fool2fish** [comment]
暂不合并分支，放到 0.5.0

**Comment by lifesinger** [comment]
放到 0.5.0 吧

0.4 保持之前的约定，不增加新功能。

On Mon, Sep 2, 2013 at 9:45 AM, fool2fish notifications@github.com wrote:

> 暂不合并分支，放到 0.5.0
> 
> On Sep 1, 2013, at 11:20 PM, hui notifications@github.com wrote:
> 
> > 这个正式的估计要等到下周才能发, 明天会把最新的功能发布到另外一台机器上. 好了通知你呀.
> > 
> > —
> > Reply to this email directly or view it on GitHub.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro/issues/94#issuecomment-23637616
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by leoner** [comment]
好, 不过这个功能确实比较实用, 现在我在测试过程中, 如果某个浏览器有问题(特别是 ie) 就很麻烦.  如果有这个功能, 我可以很快的先定位到大概的问题. 否则现在只能登录到虚拟机中, 然后一点点调试.手动的 alert 啥的.一点点排查.

我个人建议这个功能相对比较特殊, 属于那种投入小, 产出多的功能. 而且这个已经实现了. 可以走个例外呀. 
 并且这个功能起码可以在本周内省掉我一个小时以上的时间呀. 尤其是这两周大家都在 review alipay 的组件, ie 可能会有很多问题. 有了这个功能应该可以省去不少排查时间的.

**Comment by leoner** [comment]
```


  ie 6.0 / windows XP
  An error occurred at: src/xbox.js [line 48]
    对象不支持此属性或方法

=============================
```

尤其看到这种错误呀.

**Comment by lifesinger** [comment]
嗯，这是很实用的功能。

On Mon, Sep 2, 2013 at 2:51 PM, hui notifications@github.com wrote:

>   ie 6.0 / windows XP
>   An error occurred at: src/xbox.js [line 48]
>     对象不支持此属性或方法
> 
> # 
> 
> 尤其看到这种错误呀.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro/issues/94#issuecomment-23643357
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by fool2fish** [comment]
@lifesinger @leoner 突然想起来，我的代码出错的时候，我一般用 expect(我想看的值).to.be('not equivalent value') 来测试，然后等报错，看多个值也 ok

**Comment by lifesinger** [comment]
expect 是测试代码里的 log 信息

totoro.log 是全局任何代码里都可以输出 log 信息

On Tue, Sep 3, 2013 at 7:50 PM, fool2fish notifications@github.com wrote:

> @lifesinger https://github.com/lifesinger @leonerhttps://github.com/leoner突然想起来，我的代码出错的时候，我一般用 expect(我想看的值).
> to.be('not equivalent value') 来测试，然后等报错，看多个值也 ok
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/totorojs/totoro/issues/94#issuecomment-23706690
> .

## 

王保平 / 玉伯（射雕）
送人玫瑰手有余香

**Comment by leoner** [comment]
![snip20130925_1](https://f.cloud.github.com/assets/546535/1205998/985ca5b8-2598-11e3-88b7-3d1c6320803d.png)
最新的显示格式.
