### ISSUE TITLE
部分测试机的速度不正常的慢

### ISSUE THREAD

**Issue by afc163** [totorojs/totoro#95]
chrome 和 firefox 的跑用例的速度很慢，比 IE 还慢，导致用例超时(200ms)退出。

![](https://i.alipayobjects.com/e/201308/10Hjcm82eL.png)

**Comment by leoner** [comment]
firefox 不知道为啥比 ie9,10,11 有时候都满. 昨天还发现一个测试把  firefox 搞死了. 其他浏览器都没有问题.  最近会在仔细排查下, 看看到底是哪里的问题.

**Comment by leoner** [comment]
目前使用新开窗的方式后暂时没有发现类似问题。 等到后续发现问题再打开。
