### ISSUE TITLE
当浏览器超时时,提醒更加友好.

### ISSUE THREAD

**Issue by leoner** [totorojs/totoro#99]
目前超时的提醒不够友好.
![5b89744ecc4435a67f8761d6b5fe5cdf](https://f.cloud.github.com/assets/546535/1214912/6b892888-264f-11e3-98c4-1f19837395fd.png)

**Comment by leoner** [comment]
现在一个主要问题就是如果我测试多个浏览器, 只有一个超时的话, 现在不知道是那个超时. 只能一个个排查.

**Comment by fool2fish** [comment]
这个把timeout参数传到服务端，让服务端来控制超时就好了
